### ISSUE TITLE
.vercelignore syntax highlighting

### ISSUE THREAD

**Issue by Snailedlt** [ph1p/vercel-vscode-schemes#6]
Would be neat if this extension provided syntax highlighting for [.vercelignore](https://vercel.com/docs/deployments/vercel-ignore)

How it looks in the vercel documentation:
![image](https://github.com/user-attachments/assets/acb9acff-917f-4d7e-a367-4abc59a94490)

How it looks in vscode:
![image](https://github.com/user-attachments/assets/60d56884-17d9-49f5-85aa-fbfc1dd81c0a)

**Comment by ph1p** [comment]
Added and updated :)

**Comment by Snailedlt** [comment]
That was quick!

Seems like it works a bit differently though:
![image](https://github.com/user-attachments/assets/7d97c14c-7dae-4795-a479-d321eb956d77)


Notice how `/*` is still white

**Comment by ph1p** [comment]
Fixed it in the new version :)
